# Generated by Django 4.2.9 on 2024-01-27 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Type', models.CharField(max_length=100)),
                ('Price', models.DecimalField(decimal_places=0, max_digits=15)),
                ('Benefits', models.CharField(max_length=255)),
            ],
        ),
    ]
